In [1]:
import numpy as np

In [9]:
#1.生成一個等差數列，首數為0，尾數為20，公差為1的數列。

a = np.arange(0, 21, step=1)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

# 方法一

In [11]:
#2.呈上題，將以上數列取出偶數。
a_even = np.arange(0, 21, step=2)
a_even

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [16]:
#3.呈1題，將數列取出3的倍數。
a_odd = np.arange(0, 21, step=3)
a_odd

array([ 0,  3,  6,  9, 12, 15, 18])

# 方法二

In [21]:
#2.呈上題，將以上數列取出偶數。
a_even = a[a%2==0]
a_even

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [23]:
#3.呈1題，將數列取出3的倍數。
a_odd = a[a%3==0]
a_odd

array([ 0,  3,  6,  9, 12, 15, 18])